### ISSUE TITLE
Strange Language

### ISSUE THREAD

**Issue by samdog2727** [va-net/tutorials#3]
When I tried to use an API key to get the information for Bangkok VTBS, I used the URL https://vanet.app/api/airports/vtbs?apikey=myapikey (actually using my real API key) and I got the following screenshot back. 
![Screen Shot 2020-11-01 at 12 12 05 PM](https://user-images.githubusercontent.com/71337097/97809555-78301f80-1c3b-11eb-9497-e1225bd3acac.png)

I don't think this is how it is supposed to be.

**Comment by velocity23** [comment]
Sorry for the delay @samdog2727. Yes that’s how it’s meant to be. For issues with VANet, just message me on discord - this repo is just for tutorials.
